#!/system/bin/sh
# Watch inactive ABL writes and derive a matching boot entry without disturbing
# the entry that currently boots. update_engine closes the device after writing,
# which toybox inotifyd reports as the close-after-write event.
set -u

MODDIR=${MODDIR:-$(CDPATH= cd -- "$(dirname "$0")" 2>/dev/null && pwd)}
BY_NAME_DIR=${BY_NAME_DIR:-/dev/block/by-name}
PERSIST_MNT=${PERSIST_MNT:-/mnt/vendor/persist}
EFISP_DIR=${EFISP_DIR:-$PERSIST_MNT/efisp}
RUNTIME_DIR=${RUNTIME_DIR:-$MODDIR/tmp}
LOG_FILE=${LOG_FILE:-$RUNTIME_DIR/flash.log}
WATCH_INTERVAL=${WATCH_INTERVAL:-30}
LOCK_DIR="$RUNTIME_DIR/ota.lock"

mkdir -p "$RUNTIME_DIR" "$EFISP_DIR" 2>/dev/null || exit 1
[ -f "$LOG_FILE" ] || : > "$LOG_FILE"

log() {
  printf '[%s] OTA: %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >> "$LOG_FILE"
}

slot_from_path() {
  case "$1" in
    */abl_a) echo _a ;;
    */abl_b) echo _b ;;
    *) return 1 ;;
  esac
}

other_slot() {
  case "$1" in
    _a) echo _b ;;
    _b) echo _a ;;
    *) return 1 ;;
  esac
}

slot_id() {
  case "$1" in
    _a) echo android-a ;;
    _b) echo android-b ;;
    *) return 1 ;;
  esac
}

slot_title() {
  case "$1" in
    _a) echo 'Android (slot A)' ;;
    _b) echo 'Android (slot B)' ;;
    *) return 1 ;;
  esac
}

sha256_file() {
  sha256sum "$1" 2>/dev/null | cut -d ' ' -f1
}

read_global_mode() {
  mode=$(awk '$1 == "mode" && $2 ~ /^[012]$/ { print $2; exit }' \
    "$EFISP_DIR/canoe.cfg" 2>/dev/null)
  case "$mode" in 0|1|2) echo "$mode" ;; *) echo 1 ;; esac
}

read_entry_mode() {
  wanted="$1"
  fallback="$2"
  mode=$(awk -v wanted="$wanted" '
    $1 == "entry" { in_entry = ($2 == wanted); next }
    in_entry && $1 == "mode" && $2 ~ /^[012]$/ { print $2; exit }
  ' "$EFISP_DIR/canoe.cfg" 2>/dev/null)
  case "$mode" in 0|1|2) echo "$mode" ;; *) echo "$fallback" ;; esac
}

read_entry_title() {
  wanted="$1"
  fallback="$2"
  title=$(awk -v wanted="$wanted" '
    $1 == "entry" { in_entry = ($2 == wanted); next }
    in_entry && $1 == "title" { sub(/^[[:space:]]+/, "", $0); print; exit }
  ' "$EFISP_DIR/canoe.cfg" 2>/dev/null)
  [ -n "$title" ] && printf '%s\n' "$title" || printf '%s\n' "$fallback"
}

read_generation() {
  generation=$(awk '$1 == "generation" && $2 ~ /^[0-9]+$/ { print $2; exit }' \
    "$EFISP_DIR/canoe.cfg" 2>/dev/null)
  case "$generation" in ''|*[!0-9]*) generation=0 ;; esac
  if [ "$generation" -lt 4294967295 ]; then
    generation=$((generation + 1))
  fi
  echo "$generation"
}

write_entry() {
  printf 'entry %s\n  title %s\n  image %s\n  mode %s\n  role %s\n\n' \
    "$1" "$2" "$3" "$4" "$5" >> "$6"
}

write_config_for_slots() {
  changed_slot="$1"
  active_slot=$(getprop ro.boot.slot_suffix 2>/dev/null)
  case "$active_slot" in _a|_b) ;; *) active_slot=$(other_slot "$changed_slot") || active_slot=_a ;; esac
  fallback=$(read_global_mode)
  active_id=$(slot_id "$active_slot")
  active_title=$(read_entry_title "$active_id" "$(slot_title "$active_slot")")
  active_mode=$(read_entry_mode "$active_id" "$fallback")
  generation=$(read_generation)
  temp="$EFISP_DIR/canoe.cfg.tmp.$$"
  rm -f "$temp"
  {
    printf '# canoe.cfg - generated by canoe-device\n'
    printf 'version 1\n'
    printf 'generation %s\n' "$generation"
    printf 'timeout 5\n'
    printf 'default %s\n' "$active_id"
    printf 'mode %s\n' "$fallback"
    printf 'lockstate asneeded\n\n'
    write_entry "$active_id" "$active_title" boot.efi "$active_mode" active "$temp"
    for slot in _a _b; do
      [ "$slot" = "$active_slot" ] && continue
      image="boot_${slot#_}.efi"
      [ -f "$EFISP_DIR/$image" ] || continue
      id=$(slot_id "$slot")
      title=$(read_entry_title "$id" "$(slot_title "$slot")")
      mode=$(read_entry_mode "$id" "$fallback")
      write_entry "$id" "$title" "$image" "$mode" inactive "$temp"
    done
    if [ -f "$EFISP_DIR/boot_backup.efi" ]; then
      backup_mode=$(read_entry_mode android-backup "$fallback")
      write_entry android-backup 'Android (previous)' boot_backup.efi "$backup_mode" backup "$temp"
    fi
  } > "$temp" || {
    rm -f "$temp"
    return 1
  }
  mv "$temp" "$EFISP_DIR/canoe.cfg" && sync
}

remember_digest() {
  slot="$1"
  digest="$2"
  temp="$EFISP_DIR/.canoe.abl${slot}.sha256.tmp.$$"
  printf '%s\n' "$digest" > "$temp" && mv "$temp" "$EFISP_DIR/.canoe.abl${slot}.sha256" && sync
}

last_digest() {
  slot="$1"
  tr -d '[:space:]' < "$EFISP_DIR/.canoe.abl${slot}.sha256" 2>/dev/null
}

with_lock() {
  mkdir "$LOCK_DIR" 2>/dev/null || return 1
  trap 'rmdir "$LOCK_DIR" 2>/dev/null || :' EXIT
  return 0
}

remove_lock() {
  trap - EXIT
  rmdir "$LOCK_DIR" 2>/dev/null || :
}

derive_slot() {
  slot="$1"
  abl="$BY_NAME_DIR/abl$slot"
  vbmeta="$BY_NAME_DIR/vbmeta$slot"
  [ -e "$abl" ] && [ -e "$vbmeta" ] || {
    log "slot $slot is missing abl or vbmeta"
    return 1
  }
  digest=$(sha256_file "$abl")
  [ -n "$digest" ] || return 1
  old_digest=$(last_digest "$slot")
  if [ "$digest" = "$old_digest" ]; then
    log "slot $slot event ignored; ABL digest unchanged"
    return 0
  fi
  with_lock || return 0
  old_digest=$(last_digest "$slot")
  if [ "$digest" = "$old_digest" ]; then
    log "slot $slot event coalesced; ABL digest unchanged"
    remove_lock
    return 0
  fi
  work="$RUNTIME_DIR/ota$slot"
  rm -rf "$work"
  mkdir -p "$work" || { remove_lock; return 1; }
  if ! "$MODDIR/bin/extractfv" -o "$work" -v "$abl" >> "$LOG_FILE" 2>&1 ||
     ! "$MODDIR/bin/patch_abl" "$work/LinuxLoader.efi" "$work/patched.efi" \
       > "$work/patch.log" 2>&1 ||
     grep -q 'Warning: Failed to patch ABL GBL' "$work/patch.log"; then
    log "slot $slot derivation rejected: ABL is not patchable"
    remove_lock
    return 1
  fi
  if ! "$MODDIR/bin/mode2_profile" derive --vbmeta "$vbmeta" --out "$work/patched.efi.gm2p" \
       >> "$LOG_FILE" 2>&1 ||
     ! "$MODDIR/bin/mode2_profile" validate --input "$work/patched.efi.gm2p" >> "$LOG_FILE" 2>&1 ||
     ! "$MODDIR/bin/abl_tzmap" derive "$work/LinuxLoader.efi" -o "$work/patched.efi.tzmap" \
       --allow-incomplete >> "$LOG_FILE" 2>&1 ||
     ! "$MODDIR/bin/abl_tzmap" validate "$work/patched.efi.tzmap" >> "$LOG_FILE" 2>&1 ||
     ! "$MODDIR/bin/abl_tzmap" verify --sidecar "$work/patched.efi.tzmap" --abl "$abl" \
       >> "$LOG_FILE" 2>&1; then
    log "slot $slot derivation failed; keeping the previous boot entry"
    remove_lock
    return 1
  fi
  image="$EFISP_DIR/boot_${slot#_}.efi"
  cp "$work/patched.efi" "$image.tmp.$$" &&
    cp "$work/patched.efi.gm2p" "$image.gm2p.tmp.$$" &&
    cp "$work/patched.efi.tzmap" "$image.tzmap.tmp.$$" &&
    mv "$image.tmp.$$" "$image" &&
    mv "$image.gm2p.tmp.$$" "$image.gm2p" &&
    mv "$image.tzmap.tmp.$$" "$image.tzmap" || {
      rm -f "$image.tmp.$$" "$image.gm2p.tmp.$$" "$image.tzmap.tmp.$$"
      log "slot $slot derived files could not be installed"
      remove_lock
      return 1
    }
  if ! write_config_for_slots "$slot"; then
    log "slot $slot derived pair installed but canoe.cfg update failed"
    remove_lock
    return 1
  fi
  remember_digest "$slot" "$digest" || log "slot $slot digest stamp failed; next event will retry"
  log "slot $slot changed; derived new boot entry and retained previous entry"
  remove_lock
  return 0
}

# toybox inotifyd invokes this script with an event and watched path. All event
# kinds are hashed, because a close-after-write is the useful event but kernels
# and vendor toybox builds differ in their event letters.
if [ -n "${2:-}" ]; then
  event_slot=$(slot_from_path "$2" 2>/dev/null || :)
  [ -n "$event_slot" ] && derive_slot "$event_slot"
  exit 0
fi

# Seed missing stamps once; this makes first boot idempotent while preserving the
# digest guard for every subsequent OTA event.
for seed_slot in _a _b; do
  seed_abl="$BY_NAME_DIR/abl$seed_slot"
  seed_stamp="$EFISP_DIR/.canoe.abl${seed_slot}.sha256"
  if [ -e "$seed_abl" ] && [ ! -f "$seed_stamp" ]; then
    seed_digest=$(sha256_file "$seed_abl")
    [ -n "$seed_digest" ] && remember_digest "$seed_slot" "$seed_digest"
  fi
done

inotify_pid=
if command -v inotifyd >/dev/null 2>&1; then
  inotifyd "$0" "$BY_NAME_DIR/abl_a" "$BY_NAME_DIR/abl_b" >/dev/null 2>&1 &
  inotify_pid=$!
  log "watching abl_a/abl_b with toybox inotifyd close events"
else
  log "inotifyd unavailable; using 30-second ABL digest polling"
fi

while :; do
  sleep "$WATCH_INTERVAL"
  for poll_slot in _a _b; do
    derive_slot "$poll_slot"
  done
  if [ -n "$inotify_pid" ] && ! kill -0 "$inotify_pid" 2>/dev/null; then
    inotify_pid=
    log "inotifyd watch exited; digest polling remains active"
  fi
done
