# Generated by python3 scripts/imports.py mk; do not edit by hand.
# Regenerate with make bump or make import-pin ID=<id>.

CANOE_WEBUI_VERSION = 0.1.0
CANOE_WEBUI_SHA256 = fc491ad94548b865789b86b37793ece0bb7f9dbf8edc97989e27a9eea27a9620
CANOE_WEBUI_URL = file://$(CANOE_ROOT_DIR)/targets/magisk_module/webui-cache/canoe-boot-manager-0.1.0.tar.gz
CANOE_WEBUI_PATH = $(CANOE_ROOT_DIR)/targets/magisk_module/webui-cache/canoe-boot-manager-0.1.0.tar.gz

PLATFORM_TOOLS_VERSION = r37.0.0
PLATFORM_TOOLS_SHA256 = 4fe305812db074cea32903a489d061eb4454cbc90a49e8fea677f4b7af764918
PLATFORM_TOOLS_URL = https://dl.google.com/android/repository/platform-tools_r37.0.0-win.zip
