#[derive(Clone, Copy, Debug)]
pub enum TextKey {
    Entries,
    Editor,
    Bls,
    Controls,
    Slots,
    Config,
    Log,
    BootRoot,
    LocalDirectory,
    Ext4Source,
    Connect,
    Connected,
    Disconnected,
    Refresh,
    NewEntry,
    Save,
    Remove,
    SetDefault,
    Mode,
    Default,
    Id,
    Title,
    Kind,
    Role,
    Image,
    Staged,
    Install,
    Both,
    Inactive,
    InactiveAck,
    Ota,
    InstallInactive,
    Source,
    Status,
    Options,
    RawConfig,
    Language,
    English,
    Chinese,
    ReadOnly,
    AndroidReadOnly,
    NoSelection,
    OperationLog,
}

pub fn text(key: TextKey, chinese: bool) -> &'static str {
    match (key, chinese) {
        (TextKey::Entries, false) => "Entries",
        (TextKey::Entries, true) => "启动条目",
        (TextKey::Editor, false) => "Entry editor",
        (TextKey::Editor, true) => "条目编辑",
        (TextKey::Bls, false) => "BLS viewer",
        (TextKey::Bls, true) => "BLS 查看器",
        (TextKey::Controls, false) => "Defaults / modes",
        (TextKey::Controls, true) => "默认项 / 模式",
        (TextKey::Slots, false) => "Slots / install",
        (TextKey::Slots, true) => "槽位 / 安装",
        (TextKey::Config, false) => "Raw config",
        (TextKey::Config, true) => "原始配置",
        (TextKey::Log, false) => "Operation log",
        (TextKey::Log, true) => "操作日志",
        (TextKey::BootRoot, false) => "BootRoot",
        (TextKey::BootRoot, true) => "启动根目录",
        (TextKey::Connect, false) => "Connect",
        (TextKey::Connect, true) => "连接",
        (TextKey::Connected, false) => "connected",
        (TextKey::Connected, true) => "已连接",
        (TextKey::Disconnected, false) => "disconnected",
        (TextKey::Disconnected, true) => "未连接",
        (TextKey::LocalDirectory, false) => "Local directory",
        (TextKey::LocalDirectory, true) => "本地目录",
        (TextKey::Ext4Source, false) => "ext4 image / block device",
        (TextKey::Ext4Source, true) => "ext4 镜像 / 块设备",
        (TextKey::Refresh, false) => "Refresh",
        (TextKey::Refresh, true) => "刷新",
        (TextKey::NewEntry, false) => "New entry",
        (TextKey::NewEntry, true) => "新建条目",
        (TextKey::Save, false) => "Save",
        (TextKey::Save, true) => "保存",
        (TextKey::Remove, false) => "Remove",
        (TextKey::Remove, true) => "删除",
        (TextKey::SetDefault, false) => "Set default",
        (TextKey::SetDefault, true) => "设为默认",
        (TextKey::Mode, false) => "Mode",
        (TextKey::Mode, true) => "模式",
        (TextKey::Default, false) => "Default",
        (TextKey::Default, true) => "默认项",
        (TextKey::Id, false) => "ID",
        (TextKey::Id, true) => "标识",
        (TextKey::Title, false) => "Title",
        (TextKey::Title, true) => "标题",
        (TextKey::Kind, false) => "Kind",
        (TextKey::Kind, true) => "类型",
        (TextKey::Role, false) => "Role",
        (TextKey::Role, true) => "角色",
        (TextKey::Image, false) => "Image path",
        (TextKey::Image, true) => "镜像路径",
        (TextKey::Staged, false) => "Staged artifact",
        (TextKey::Staged, true) => "已暂存的产物",
        (TextKey::Install, false) => "Install",
        (TextKey::Install, true) => "安装",
        (TextKey::Both, false) => "Install to both slots",
        (TextKey::Both, true) => "安装到两个槽位",
        (TextKey::Inactive, false) => "Install to inactive slot",
        (TextKey::Inactive, true) => "安装到非活动槽位",
        (TextKey::InactiveAck, false) => {
            "I know the inactive slot status (required for inactive install)"
        }
        (TextKey::InactiveAck, true) => "我知道非活动槽位状态（安装到非活动槽位必选）",
        (TextKey::Ota, false) => "OTA apply",
        (TextKey::Ota, true) => "OTA 应用",
        (TextKey::InstallInactive, false) => "Install to inactive slot",
        (TextKey::InstallInactive, true) => "安装到非活动槽位",
        (TextKey::Source, false) => "Source",
        (TextKey::Source, true) => "来源",
        (TextKey::Status, false) => "Status",
        (TextKey::Status, true) => "状态",
        (TextKey::Options, false) => "Options",
        (TextKey::Options, true) => "选项",
        (TextKey::RawConfig, false) => "Configuration document returned by config.show",
        (TextKey::RawConfig, true) => "config.show 返回的配置文档",
        (TextKey::Language, false) => "Language",
        (TextKey::Language, true) => "语言",
        (TextKey::English, false) => "English",
        (TextKey::English, true) => "English",
        (TextKey::Chinese, false) => "中文",
        (TextKey::Chinese, true) => "中文",
        (TextKey::ReadOnly, false) => "read-only",
        (TextKey::ReadOnly, true) => "只读",
        (TextKey::AndroidReadOnly, false) => "Android fields are read-only in this lane",
        (TextKey::AndroidReadOnly, true) => "Android 字段在此版本中为只读",
        (TextKey::NoSelection, false) => "Select an entry to edit",
        (TextKey::NoSelection, true) => "请选择条目进行编辑",
        (TextKey::OperationLog, false) => "Bounded protocol activity (latest first)",
        (TextKey::OperationLog, true) => "有界协议活动（最新在前）",
    }
}
