#!/usr/bin/env python3
"""Generate CanoeMsdVariantData.c from the bundled mass-storage blob.

Called by submodules/uefi/Makefile before every build. A missing blob yields
an empty array, which builds fine and means every export uses the platform's
own driver.
"""

from __future__ import annotations

import sys
from pathlib import Path

HEADER = """/*
 * Generated by embed_variant.py. Do not edit; not committed.
 */
#include <Uefi.h>

"""


def emit_bytes(name: str, data: bytes) -> str:
    rows = []
    for i in range(0, len(data), 16):
        rows.append("  " + ", ".join(f"0x{b:02x}" for b in data[i : i + 16]) + ",")
    return f"STATIC CONST UINT8 {name}[{len(data)}] = {{\n" + "\n".join(rows) + "\n};\n\n"


def main() -> int:
    blob = Path(sys.argv[1])
    out = Path(sys.argv[2])

    body = HEADER
    data = b""
    if blob.is_file():
        candidate = blob.read_bytes()
        if candidate[:2] == b"MZ":
            data = candidate
        else:
            print(f"embed_variant: {blob} is not a PE image, skipping", file=sys.stderr)
    else:
        print(f"embed_variant: {blob} missing, building without a bundled driver",
              file=sys.stderr)

    if data:
        body += emit_bytes("mCanoeMsdImage", data)
        body += "CONST UINT8 *gCanoeMsdVariant = mCanoeMsdImage;\n"
    else:
        body += "CONST UINT8 *gCanoeMsdVariant = NULL;\n"
    body += f"CONST UINTN gCanoeMsdVariantSize = {len(data)};\n"

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body)
    print(f"embed_variant: {out} -> {len(data)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
