#!/usr/bin/env python3
"""Generate CanoeMsdVariantData.c from the canoe-msd variant blob.

Called by submodules/uefi/Makefile before every build. When the blob is
present the array carries the bundled UsbMsdDxe variant; when absent the
stub keeps the build working and every export falls back to the resident
driver. The generated file is not committed.
"""

import sys
from pathlib import Path

HEADER = """/*
 * Generated by embed_variant.py from the canoe-msd submodule's variant blob.
 * Do not edit; not committed.
 */
#include <Uefi.h>

"""

def main() -> int:
    src = Path(sys.argv[1])
    out = Path(sys.argv[2])
    if src.is_file():
        data = src.read_bytes()
        lines = []
        for i in range(0, len(data), 16):
            lines.append("  " + ", ".join(f"0x{b:02x}" for b in data[i : i + 16]) + ",")
        body = HEADER
        body += f"UINT8 gCanoeMsdVariant[{len(data)}] = {{\n" + "\n".join(lines) + "\n};\n"
        body += f"UINTN gCanoeMsdVariantSize = {len(data)};\n"
    else:
        body = HEADER
        body += "UINT8 gCanoeMsdVariant[1] = {0};\n"
        body += "UINTN gCanoeMsdVariantSize = 0;\n"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body)
    print(f"embed_variant: {out} ({'blob absent, stub' if not src.is_file() else f'{src.name}, {src.stat().st_size} bytes'})")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
