#!/bin/sh
#
# canoe_device_install.sh - the persist install transaction, run ON THE DEVICE.
#
# This is the single source of truth for the install transaction. The host-side
# driver (`canoe install`, one Python implementation shared by the Linux and the
# Windows toolkit) and the on-device module both only stage files and invoke
# this script. It stays shell because it runs on the device, where there is no
# interpreter to ship.
#
#   sh canoe_device_install.sh <staging_dir> <efisp_dir> [<efisp_dev> <backup>]
#
#   staging_dir  holds boot.efi, boot.efi.gm2p and boot.efi.tzmap,
#                optionally tools/, and optionally BDS.efi. It should live on the
#                same filesystem as efisp_dir so the commit is a rename.
#   efisp_dir    the boot root, e.g. /persist/efisp or /mnt/vendor/persist/efisp
#   efisp_dev    block device for the efisp partition; omit to skip the BDS write
#   backup       where to write the pre-write copy of efisp_dev
#
# Every absolute device path arrives as an argument. Nothing is hardcoded, which
# is what lets the transaction be exercised directly on a host against ordinary
# directories and a regular file standing in for the block device.
#
# Transaction:
#   1. validate the staged set (sizes are exact contract values)
#   2. snapshot everything the commit will overwrite: the live triplet,
#      existing backup generation, canoe.cfg, tools/ and .canoe.gen
#   3. set aside foreign boot-root entries, then commit live -> boot_backup.*,
#      staged -> live
#   4. write canoe.cfg and install tools, write the informational .canoe.gen
#      stamp, sync
#   5. optionally back up efisp, write the BDS, verify it byte-for-byte
#
# The efisp partition contains only BDS.efi. Menu state lives in the
# atomically-written canoe.cfg file; the abl partition is never touched.
set -eu

STAGING=${1:-}
D=${2:-}
EFISP_DEV=${3:-}
BACKUP=${4:-}
STAGING_NAME=${STAGING##*/}
ACTIVE_SLOT=${5:-${CANOE_ACTIVE_SLOT:-}}
if [ -z "$ACTIVE_SLOT" ] && command -v getprop >/dev/null 2>&1; then
  ACTIVE_SLOT=$(getprop ro.boot.slot_suffix 2>/dev/null || :)
fi
case "$ACTIVE_SLOT" in _a|_b) ;; *) ACTIVE_SLOT=_a ;; esac
say()  { printf 'canoe-device: %s\n' "$1"; }
mark() { printf 'CANOE-MARK: %s\n' "$1"; }
die()  { printf 'canoe-device: error: %s\n' "$1" >&2; exit 1; }

[ -n "$STAGING" ] && [ -n "$D" ] || \
  die "usage: canoe_device_install.sh <staging_dir> <efisp_dir> [<efisp_dev> <backup>]"
[ -d "$STAGING" ] || die "staging directory not found: $STAGING"
if [ -n "$EFISP_DEV" ] && [ -z "$BACKUP" ]; then
  die "a backup path is required when an efisp device is given"
fi

size_of() { wc -c < "$1" | tr -d ' \n\r'; }
sha256_file() {
  sha256sum "$1" 2>/dev/null | cut -d ' ' -f1
}

config_global_mode() {
  config_mode=$(awk '$1 == "mode" && $2 ~ /^[012]$/ { print $2; exit }' \
    "$1" 2>/dev/null)
  case "$config_mode" in 0|1|2) echo "$config_mode" ;; *) echo 1 ;; esac
}

config_entry_mode() {
  config_target="$1"
  config_id="$2"
  config_default="$3"
  config_mode=$(awk -v wanted="$config_id" '
    $1 == "entry" { in_entry = ($2 == wanted); next }
    in_entry && $1 == "mode" && $2 ~ /^[012]$/ { print $2; exit }
  ' "$config_target" 2>/dev/null)
  case "$config_mode" in 0|1|2) echo "$config_mode" ;; *) echo "$config_default" ;; esac
}

# Writes to stdout, never to a named file: write_canoe_config wraps the whole
# document in one redirect, and a second writer opening the same path with `>>`
# would keep its own offset. That happened to work only because every header
# line was emitted before every entry; one reordered printf would have
# silently overwritten entry text.
write_config_entry() {
  printf 'entry %s\n  title %s\n  image %s\n  mode %s\n  role %s\n\n' \
    "$1" "$2" "$3" "$4" "$5"
}

write_canoe_config() {
  config_output_dir="$1"
  config_output="$config_output_dir/canoe.cfg"
  config_active=android-a
  config_active_title='Android (slot A)'
  if [ "$ACTIVE_SLOT" = "_b" ]; then
    config_active=android-b
    config_active_title='Android (slot B)'
  fi
  config_fallback=$(config_global_mode "$config_output")
  config_active_mode=$(config_entry_mode "$config_output" "$config_active" "$config_fallback")
  config_generation=$(awk '$1 == "generation" && $2 ~ /^[0-9]+$/ { print $2; exit }' \
    "$config_output" 2>/dev/null)
  case "$config_generation" in
    ''|*[!0-9]*) config_generation=0 ;;
  esac
  if [ "$config_generation" -lt 4294967295 ]; then
    config_generation=$((config_generation + 1))
  fi
  config_temp="$config_output.tmp.$$"
  rm -f "$config_temp"
  {
    printf '# canoe.cfg - generated by canoe-device\n'
    printf 'version 1\n'
    printf 'generation %s\n' "$config_generation"
    printf 'timeout 5\n'
    printf 'default %s\n' "$config_active"
    printf 'mode %s\n' "$config_fallback"
    printf 'lockstate asneeded\n\n'
    write_config_entry "$config_active" "$config_active_title" boot.efi \
      "$config_active_mode" active
    config_inactive=android-b
    config_inactive_title='Android (slot B)'
    [ "$config_active" = android-b ] && {
      config_inactive=android-a
      config_inactive_title='Android (slot A)'
    }
    config_inactive_image="boot_${config_inactive#android-}.efi"
    if [ -f "$config_output_dir/$config_inactive_image" ]; then
      config_inactive_mode=$(config_entry_mode "$config_output" "$config_inactive" "$config_fallback")
      write_config_entry "$config_inactive" "$config_inactive_title" "$config_inactive_image" \
        "$config_inactive_mode" inactive
    fi
    if [ -f "$config_output_dir/boot_backup.efi" ]; then
      config_backup_mode=$(config_entry_mode "$config_output" android-backup "$config_fallback")
      write_config_entry android-backup 'Android (previous)' boot_backup.efi \
        "$config_backup_mode" backup
    fi
  } > "$config_temp" || {
    rm -f "$config_temp"
    return 1
  }
  mv "$config_temp" "$config_output" && sync
}
# ------------------------------------------------------ 1. validate staged ---
[ -s "$STAGING/boot.efi" ]       || die "staged boot.efi is missing or empty"
[ -s "$STAGING/boot.efi.gm2p" ]  || die "staged boot.efi.gm2p is missing or empty"
[ -s "$STAGING/boot.efi.tzmap" ] || die "staged boot.efi.tzmap is missing or empty"
gm2p=$(size_of "$STAGING/boot.efi.gm2p")
tzmap=$(size_of "$STAGING/boot.efi.tzmap")
[ "$gm2p" = 120 ]  || die "boot.efi.gm2p must be exactly 120 bytes, got $gm2p"
[ "$tzmap" = 256 ] || die "boot.efi.tzmap must be exactly 256 bytes, got $tzmap"
if [ -n "$EFISP_DEV" ]; then
  [ -s "$STAGING/BDS.efi" ] || die "staged BDS.efi is missing or empty"
  [ -e "$EFISP_DEV" ]       || die "efisp device not found: $EFISP_DEV"
fi
mark "staged-set-validated gm2p=$gm2p tzmap=$tzmap"

mkdir -p "$D" "$D/tools" || die "could not create $D"

# ------------------------------------------- 2. snapshot what commit touches --
# The boot-root menu state is part of the transaction: a rollback that restored
# only the triplet would leave the old loader beside the new canoe.cfg and tools.
rm -rf "$D"/.canoe.live.* "$D"/.canoe.oldbak.* "$D/.canoe.oldmenu" \
  "$D/.canoe.oldgen" "$D/.canoe.oldcfg" "$D/.canoe.oldcfg.absent" \
  "$D/.canoe.foreign.moves" "$D/.canoe.gen.tmp" "$D/.canoe.cfg.tmp."* || :
mkdir -p "$D/.canoe.oldmenu" || die "could not create the snapshot directory"

[ -s "$D/boot.efi" ]              && cp -f "$D/boot.efi" "$D/.canoe.live.efi"
[ -s "$D/boot.efi.gm2p" ]         && cp -f "$D/boot.efi.gm2p" "$D/.canoe.live.gm2p"
[ -s "$D/boot.efi.tzmap" ]        && cp -f "$D/boot.efi.tzmap" "$D/.canoe.live.tzmap"
[ -s "$D/boot_backup.efi" ]       && cp -f "$D/boot_backup.efi" "$D/.canoe.oldbak.efi"
[ -s "$D/boot_backup.efi.gm2p" ]  && cp -f "$D/boot_backup.efi.gm2p" "$D/.canoe.oldbak.gm2p"
[ -s "$D/boot_backup.efi.tzmap" ] && cp -f "$D/boot_backup.efi.tzmap" "$D/.canoe.oldbak.tzmap"
if [ -e "$D/canoe.cfg" ]; then
  cp -f "$D/canoe.cfg" "$D/.canoe.oldcfg" || die "could not snapshot canoe.cfg"
else
  : > "$D/.canoe.oldcfg.absent" || die "could not snapshot absent canoe.cfg"
fi
if [ -e "$D/.canoe.gen" ]; then
  cp -f "$D/.canoe.gen" "$D/.canoe.oldgen" || die "could not snapshot .canoe.gen"
fi
if [ -d "$D/tools" ]; then
  mkdir -p "$D/.canoe.oldmenu/tools"
  for t in "$D"/tools/*; do
    [ -e "$t" ] || continue
    cp -f "$t" "$D/.canoe.oldmenu/tools/" || die "could not snapshot $(basename "$t")"
  done
fi
sync || :

if [ -s "$D/.canoe.live.efi" ]; then
  mark "previous-generation-saved"
else
  mark "first-install"
fi

COMMITTED=no

FOREIGN_EXISTED=no
[ -d "$D/.canoe.foreign" ] && FOREIGN_EXISTED=yes

set_aside_foreign() {
  foreign_entry=
  for foreign_entry in "$D"/* "$D"/.[!.]* "$D"/..?*; do
    [ -e "$foreign_entry" ] || [ -L "$foreign_entry" ] || continue
    foreign_name=${foreign_entry##*/}
    case "$foreign_name" in
      boot.efi|boot.efi.gm2p|boot.efi.tzmap|boot_backup.efi|boot_backup.efi.gm2p|boot_backup.efi.tzmap|canoe.cfg|tools|.canoe.gen|.canoe.foreign|.canoe.live.*|.canoe.oldbak.*|.canoe.oldmenu|.canoe.oldgen|.canoe.oldcfg|.canoe.oldcfg.absent|.canoe.foreign.moves|.canoe.gen.tmp|.canoe.cfg.tmp.*|"$STAGING_NAME")
        continue
        ;;
    esac
    if [ ! -d "$D/.canoe.foreign" ]; then
      mkdir -p "$D/.canoe.foreign" || fail "could not create .canoe.foreign"
    fi
    foreign_target="$D/.canoe.foreign/$foreign_name"
    foreign_suffix=1
    while [ -e "$foreign_target" ] || [ -L "$foreign_target" ]; do
      foreign_target="$D/.canoe.foreign/$foreign_name.$foreign_suffix"
      foreign_suffix=$((foreign_suffix + 1))
    done
    foreign_target_name=${foreign_target##*/}
    printf '%s\t%s\n' "$foreign_name" "$foreign_target_name" >> "$D/.canoe.foreign.moves" ||
      fail "could not record foreign entry $foreign_name"
    mv -f "$foreign_entry" "$foreign_target" ||
      fail "could not set aside foreign entry $foreign_name"
    say "set aside foreign entry $foreign_name in .canoe.foreign/$foreign_target_name"
  done
}

restore_foreign() {
  [ -f "$D/.canoe.foreign.moves" ] || return 0
  old_ifs=$IFS
  IFS='	'
  while read -r foreign_name foreign_target_name; do
    [ -n "$foreign_name" ] || continue
    mv -f "$D/.canoe.foreign/$foreign_target_name" "$D/$foreign_name" || :
  done < "$D/.canoe.foreign.moves"
  IFS=$old_ifs
  if [ "$FOREIGN_EXISTED" = no ]; then
    rmdir "$D/.canoe.foreign" 2>/dev/null || :
  fi
}

restore_pair() {
  [ "$COMMITTED" = no ] && return 0
  say "restoring the previous generation"
  if [ -s "$D/.canoe.live.efi" ]; then
    cp -f "$D/.canoe.live.efi" "$D/boot.efi" || :
    if [ -s "$D/.canoe.live.gm2p" ]; then
      cp -f "$D/.canoe.live.gm2p" "$D/boot.efi.gm2p" || :
    else
      rm -f "$D/boot.efi.gm2p"
    fi
    if [ -s "$D/.canoe.live.tzmap" ]; then
      cp -f "$D/.canoe.live.tzmap" "$D/boot.efi.tzmap" || :
    else
      rm -f "$D/boot.efi.tzmap"
    fi
  else
    # There was no live generation: a failed first install must not leave a
    # partial boot.efi behind.
    rm -f "$D/boot.efi" "$D/boot.efi.gm2p" "$D/boot.efi.tzmap"
  fi

  if [ -s "$D/.canoe.oldbak.efi" ]; then
    cp -f "$D/.canoe.oldbak.efi" "$D/boot_backup.efi" || :
  else
    rm -f "$D/boot_backup.efi"
  fi
  if [ -s "$D/.canoe.oldbak.gm2p" ]; then
    cp -f "$D/.canoe.oldbak.gm2p" "$D/boot_backup.efi.gm2p" || :
  else
    rm -f "$D/boot_backup.efi.gm2p"
  fi
  if [ -s "$D/.canoe.oldbak.tzmap" ]; then
    cp -f "$D/.canoe.oldbak.tzmap" "$D/boot_backup.efi.tzmap" || :
  else
    rm -f "$D/boot_backup.efi.tzmap"
  fi

  rm -rf "$D/tools" || :
  mkdir -p "$D/tools" || :
  if [ -d "$D/.canoe.oldmenu/tools" ]; then
    for t in "$D"/.canoe.oldmenu/tools/*; do
      [ -e "$t" ] || continue
      cp -f "$t" "$D/tools/" || :
    done
  fi

  if [ -e "$D/.canoe.oldgen" ]; then
    cp -f "$D/.canoe.oldgen" "$D/.canoe.gen" || :
  else
    rm -f "$D/.canoe.gen"
  fi
  if [ -e "$D/.canoe.oldcfg" ]; then
    cp -f "$D/.canoe.oldcfg" "$D/canoe.cfg" || :
  elif [ -e "$D/.canoe.oldcfg.absent" ]; then
    rm -f "$D/canoe.cfg"
  fi


  sync || :
  mark "pair-restored"
}

restore_efisp() {
  [ -n "$EFISP_DEV" ] && [ -s "$BACKUP" ] || return 0
  say "restoring $EFISP_DEV from $BACKUP"
  if dd if="$BACKUP" of="$EFISP_DEV" bs=4M conv=fsync 2>/dev/null; then
    sync || :
    mark "efisp-restored"
  else
    say "efisp restore FAILED; reflash it from $BACKUP before rebooting"
    mark "efisp-restore-failed"
  fi
}

cleanup() {
  rm -rf "$D"/.canoe.live.* "$D"/.canoe.oldbak.* "$D/.canoe.oldmenu" \
    "$D/.canoe.oldgen" "$D/.canoe.oldcfg" "$D/.canoe.oldcfg.absent" \
    "$D/.canoe.foreign.moves" "$D/.canoe.gen.tmp" 2>/dev/null || :
}

fail() {
  restore_efisp
  restore_foreign
  restore_pair
  cleanup
  die "$1"
}

# ------------------------------------------------------------- 3. commit -----
set_aside_foreign

COMMITTED=yes
if [ -s "$D/.canoe.live.efi" ]; then
  cp -f "$D/.canoe.live.efi" "$D/boot_backup.efi" || fail "could not write boot_backup.efi"
  # A backup without its matching sidecar is worse than no sidecar at all.
  if [ -s "$D/.canoe.live.gm2p" ]; then
    cp -f "$D/.canoe.live.gm2p" "$D/boot_backup.efi.gm2p" || fail "could not write boot_backup.efi.gm2p"
  else
    rm -f "$D/boot_backup.efi.gm2p"
  fi
  if [ -s "$D/.canoe.live.tzmap" ]; then
    cp -f "$D/.canoe.live.tzmap" "$D/boot_backup.efi.tzmap" || fail "could not write boot_backup.efi.tzmap"
  else
    rm -f "$D/boot_backup.efi.tzmap"
  fi
fi
mv -f "$STAGING/boot.efi"       "$D/boot.efi"       || fail "could not install boot.efi"
mv -f "$STAGING/boot.efi.gm2p"  "$D/boot.efi.gm2p"  || fail "could not install boot.efi.gm2p"
mv -f "$STAGING/boot.efi.tzmap" "$D/boot.efi.tzmap" || fail "could not install boot.efi.tzmap"
mark "committed"

# ----------------------------------------------- 4. boot menu tree + sync ----
if [ -d "$STAGING/tools" ]; then
  for t in "$STAGING"/tools/*; do
    [ -e "$t" ] || continue

    cp -f "$t" "$D/tools/" || fail "could not install $(basename "$t")"
  done
fi
write_canoe_config "$D" || fail "could not install canoe.cfg"
sync || fail "sync of the persist tree failed"
mark "tree-synced"
write_generation() {
  boot_digest=$(sha256_file "$D/boot.efi")
  [ -n "$boot_digest" ] || fail "could not hash installed boot.efi"
  gm2p_digest=$(sha256_file "$D/boot.efi.gm2p")
  [ -n "$gm2p_digest" ] || fail "could not hash installed boot.efi.gm2p"
  tzmap_digest=$(sha256_file "$D/boot.efi.tzmap")
  [ -n "$tzmap_digest" ] || fail "could not hash installed boot.efi.tzmap"
  bds_field=-
  if [ -n "$EFISP_DEV" ]; then
    bds_field=$(sha256_file "$STAGING/BDS.efi")
    [ -n "$bds_field" ] || fail "could not hash installed BDS.efi"
  fi
  printf 'CANOEG1|%s|%s|%s|%s\n' "$bds_field" "$boot_digest" "$gm2p_digest" "$tzmap_digest" > "$D/.canoe.gen.tmp" ||
    fail "could not write .canoe.gen"
  mv -f "$D/.canoe.gen.tmp" "$D/.canoe.gen" || fail "could not install .canoe.gen"
  mark "generation-stamped"
}

write_generation

# ---------------------------------------------------------------- 5. BDS -----
if [ -n "$EFISP_DEV" ]; then
  part_bytes=$(blockdev --getsize64 "$EFISP_DEV" 2>/dev/null || size_of "$EFISP_DEV")
  case "$part_bytes" in
    ''|*[!0-9]*) fail "could not read the size of $EFISP_DEV" ;;
  esac
  bds_bytes=$(size_of "$STAGING/BDS.efi")
  [ "$bds_bytes" -le "$part_bytes" ] || fail "BDS.efi does not fit in $EFISP_DEV"
  if [ "$part_bytes" -lt 1048576 ]; then
    say "WARNING: $EFISP_DEV is under 1 MiB; the BDS mode store needs that much slack and will fall back to Mode 1"
  fi
  mark "efisp-size part=$part_bytes bds=$bds_bytes"

  dd if="$EFISP_DEV" of="$BACKUP" bs=4M 2>/dev/null || fail "could not back up $EFISP_DEV"
  [ "$(size_of "$BACKUP")" = "$part_bytes" ] || fail "backup of $EFISP_DEV is the wrong size"
  mark "efisp-backed-up"

  blockdev --setrw "$EFISP_DEV" 2>/dev/null || :
  if ! dd if="$STAGING/BDS.efi" of="$EFISP_DEV" bs=4M conv=fsync 2>/dev/null; then
    fail "write to $EFISP_DEV failed"
  fi
  sync || :

  # Compare the full written length, not a magic prefix.
  if ! dd if="$EFISP_DEV" of="$STAGING/readback.img" bs="$bds_bytes" count=1 2>/dev/null; then
    fail "could not read back $EFISP_DEV"
  fi
  if ! cmp "$STAGING/BDS.efi" "$STAGING/readback.img" >/dev/null 2>&1; then
    fail "verification of $EFISP_DEV failed"
  fi
  rm -f "$STAGING/readback.img"
  mark "efisp-verified bytes=$bds_bytes"
fi

cleanup
mark "done"
say "install complete"
